# Generated by Django 4.0.4 on 2022-07-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_avatarblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvatarBlog',
        ),
    ]
